import time


def myFunction():
    print('             *  ')
    print('             * ')
    print('             |')
    print('            /_\ ')
    print('           /|||\ ')
    print('          /-|||-\ ')
    print('         /--|||--\ ')
    print('       |/---|||---\| ')
    print('        |/_\-/_\| ')
    print('          ?   ? ')
    print()
    print('                          |  ')
    print('                         /_\ ')
    print('                        /|||\ ')
    print('                       /-|||-\ ')
    print('                      /--|||--\ ')
    print('                    |/---|||---\|  ')
    print('                      |/_\-/_\|  ')
    print('                        ?   ? ')
    print('                                                                   |  ')
    print('                                                                  /_\ ')
    print('                                                                 /|||\ ')
    print('                                                                /-|||-\ ')
    print('                                                               /--|||--\ ')
    print('                                                             |/---|||---\|  ')
    print('                                                               |/_\-/_\|  ')
    print('                                                                 ?   ? ')
    print('             *  ')
    print('             * ')
    print('             |')
    print('            /_\ ')
    print('           /|||\ ')
    print('          /-|||-\ ')
    print('         /--|||--\ ')
    print('       |/---|||---\| ')
    print('        |/_\-/_\| ')
    print('          ?   ? ')
    print()
    print('                          |  ')
    print('                         /_\ ')
    print('                        /|||\ ')
    print('                       /-|||-\ ')
    print('                      /--|||--\ ')
    print('                    |/---|||---\|  ')
    print('                      |/_\-/_\|  ')
    print('                        ?   ? ')
    print('                                                                   |  ')
    print('                                                                  /_\ ')
    print('                                                                 /|||\ ')
    print('                                                                /-|||-\ ')
    print('                                                               /--|||--\ ')
    print('                                                             |/---|||---\|  ')
    print('                                                               |/_\-/_\|  ')
    print('                                                                 ?   ? ')
    print('                            *  ')
    print('                            * ')
    print('                            |')
    print('                           /_\ ')
    print('                          /|||\ ')
    print('                         /-|||-\ ')
    print('                        /--|||--\ ')
    print('                      |/---|||---\| ')
    print('                        |/_\-/_\| ')
    print('                          ?   ? ')
    print()
    print('                                                        |  ')
    print('                                                       /_\ ')
    print('                                                      /|||\ ')
    print('                                                     /-|||-\ ')
    print('                                                    /--|||--\ ')
    print('                                                  |/---|||---\|  ')
    print('                                                    |/_\-/_\|  ')
    print('                                                      ?   ? ')
    print('                                                                                                |  ')
    print('                                                                                               /_\ ')
    print('                                                                                              /|||\ ')
    print('                                                                                             /-|||-\ ')
    print('                                                                                            /--|||--\ ')
    print('                                                                                          |/---|||---\|  ')
    print('                                                                                            |/_\-/_\|  ')
    print('                                                                                              ?   ? ')
    print('.....................................................................................................|||||||||||')
    print('                      |____/\___  RRRRR    OOOOO   MMM        MMM       AAA       NNN     NN\   ||   /|')
    print('                      |___/||\___ RR   RR  OO    OO MM M      M MM     AA   AA     NN NN  NN_\  ||  /_|')
    print('                      |__/  || \__ RRRRR   OO     OO MM MM MM MM    AA     AA    NN  NN NN__\ || /__|')
    print('                      |_/    ||  \_ RR   RR  OO    OO  MM  MMM   MM   AAAAAAAA   NN    N NN___\||/___|')
    print('                      |/      ||   \ RR     RR OOOOO   MM            MM  AAAA  AAAA  NN     NNN____\/____|')
    print('......................|||||||||||..............................................................')
    print()
    print('---------------------------------------------------------------------------------------------------------------')
    print('        |____/\____|RRRRR       AAA     BBBBB  BBBBB  IIII TTTTTT WW       WW       WW EEEEE BBBBB |\   ||   /|')
    print('        |___/||\___|RR  RR     AA AA    BB  BB BB  BB  II  T TT T  WW     WWWW     WW  EE    BB  BB|_\  ||  /_|')
    print('        |__/ || \__|RRRRR     AA   AA   BBBBB  BBBBB   II    TT     WW   WW  WW   WW   EEE   BBBBB |__\ || /__|')
    print('        |_/  ||  \_|RR  RR   AAAAAAAAA  BB  BB BB  BB  II    TT      WW WW    WW WW    EE    BB  BB|___\||/___|')
    print('        |/   ||   \|RR   RR AAAA   AAAA BBBBB  BBBBB  IIII   TT       WWW      WWW     EEEEE BBBBB |____\/____|')
    print('---------------------------------------------------------------------------------------------------------------')

    i = 0
    while i == 3:
        myFunction()
        i ++ 1
        time.sleep(0.4)

myFunction()
